In [1]:
import numpy as np

In [2]:
X = np.array([[5],[10]])

In [3]:
X.shape

(2, 1)

In [4]:
W = np.array([[1,1],[1,2],[-1,-1],[-2,-2]])
W.shape

(4, 2)

In [7]:
W0 = np.array([[1,1,1,1]]).T
W0.shape

(4, 1)

In [8]:
(W@X+W0)

array([[ 16],
       [ 26],
       [-14],
       [-29]])

In [13]:
Z1 = (W@X+W0)

In [9]:
(W@X+W0).shape

(4, 1)

In [10]:
V = np.array([[1,1,1,1],[-1,-1,-1,-1]])

In [11]:
V.shape

(2, 4)

In [12]:
V0 = np.array([[2],[-2]])
V0.shape

(2, 1)

In [14]:
V@Z1+V0

array([[ 1],
       [-1]])

In [40]:
class NN():
    def __init__(self,X):
        self.X = X
        self.W = np.random.randn(4,X.shape[0])
        self.W0 = np.array([[1,1,1,1]]).T
        self.V = np.random.randn(2,(self.W@self.X).shape[0])## don't do this
        self.V0 = np.array([[2],[-2]])
    
    def relu(self,z):
        z[z<0]=0
        return z
    
    def softmax(self, z):
        return np.exp(z)/np.sum(np.exp(z))
    
    def forward_z(self):
        Z1 = self.W@self.X+self.W0
        Z2 = self.V@Z1+self.V0
        return {'z1':Z1,'z2':Z2}
    def forward(self):
        Z1 = self.W@self.X+self.W0
        A1 = self.relu(Z1)
        Z2 = self.V@A1+self.V0
        A2 = self.softmax(Z2)
        return A2

In [41]:
n = NN(X)

In [44]:
n.forward()

array([[0.99406654],
       [0.00593346]])

In [54]:
predictions = [[0.80],[0.20]]
labels = [[0],[1]]
tol = 1e-50
loss = []
for pred,act in zip(predictions,labels):
    loss.append(-1*np.log(pred[0]*act[0]+tol))
sum(loss)

116.73869256213639

In [61]:
predictions = [[0.80],[0.20]]
labels = [[1],[0]]
def ce(preds,actuals):
    tol = 1e-50
    loss = []
    for pred,act in zip(preds,actuals):
        loss.append(-1*np.log(pred[0]*act[0]+tol))
    return sum(loss)   

In [62]:
ce(predictions,labels)

115.3523982010165

**Grad Descent**

Minimize: $f(x) = x^2+4x$

- Start with x = -3, $x_old$
- Find grad of f
- x_new = x_old-grad*lr -> A
- Continue to do A for a large number of times or till the time the value of f(x) doesn't change much from one iter to another


In [63]:
def grad(x):
    return 2*x+4

In [65]:
x = -3
lr = 0.0001
for i in range(10000000):
    g = grad(x)
    x_new = x-g*lr###
    x = x_new
print(x)

-2.0000000000011102


**minimize**

$$(w-0)^2+(w-0.2)^2+(w-0.4)^2+(w-0.9)^2+(w-1)^2$$

In [66]:
def grad(w):
    return 10*w-5
w = 1
lr = 0.002
for i in range(10000):
    g = grad(w)
    w_new = w-lr*g
    w = w_new
print(w)

0.5000000000000028


In [70]:
import pandas as pd
data = pd.read_csv("../data/regression.csv")

In [71]:
data.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0        8.0         307.0       130.0  3504.0          12.0  70.0   
1  15.0        8.0         350.0       165.0  3693.0          11.5  70.0   

   origin  
0     1.0  
1     1.0

In [76]:
X = data[['cylinders']].copy()
X['ones'] = 1
X = X[['ones','cylinders']]
X.head(2)
y = data['mpg'].values

In [80]:
y.shape

(398,)

In [81]:
y = y.reshape((y.shape[0],1))

In [82]:
y.shape

(398, 1)

In [77]:
X = X.values

In [78]:
X.shape

(398, 2)

In [79]:
W = np.array([[0.2],[0.3]])
W.shape

(2, 1)

In [83]:
def grad(W):
    g = -2*X.T@(X@W-y)
    return g/y.shape[0]

In [95]:
W = np.array([[0.2],[0.3]])##
lr = 0.00001
for i in range(100):
    g = grad(W)
    W_new = W-lr*g
    W = W_new
print(W)

[[0.15541734]
 [0.07848364]]


In [100]:
X_one = X[:,1]

In [102]:
X_one = X_one.reshape((398,1))

In [104]:
data = pd.read_csv("../data/classification.csv")

In [105]:
data.head(2)

No_pregnant  Plasma_glucose  Blood_pres  Skin_thick  Serum_insu   BMI  \
0            6             148          72          35           0  33.6   
1            1              85          66          29           0  26.6   

   Diabetes_func  Age  Class  
0          0.627   50      1  
1          0.351   31      0

In [ ]:
## No_pregnant-x1
## y - > class

$grad = X^T(p-y)\frac{1}{n}$

$p = \frac{1}{1+e^-z}$

$z = XW$

In [106]:
X = data[['No_pregnant']].copy()
X['Ones'] = 1
X = X[['Ones','No_pregnant']].values

In [107]:
y = data['Class'].values

In [108]:
y.shape

(768,)

In [109]:
y = y.reshape((768,1))

In [110]:
def probs(X,W):
    z = X@W
    return 1/(1+np.exp(-z))

In [111]:
def grad(W):
    p = probs(X,W)
    return X.T@(p-y)/y.shape[0]

In [112]:
W = np.array([[1],[2]])
lr = 0.01
for i in range(1000):
    g = grad(W)
    W_n = W-g*lr
    W = W_n
print(W)

[[-0.49863269]
 [ 0.03724324]]


### Autograd

In [113]:
import torch

/Users/gunnvantsaini/miniforge3/envs/dl/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


$x^2+4x$

In [115]:
x = torch.tensor(0.0,requires_grad=True)

In [116]:
z = x**2+4*x

In [117]:
z.backward()

In [119]:
x.grad

tensor(4.)

In [121]:
z = x**2+4*x
z.backward()

In [122]:
x.grad

tensor(8.)

In [128]:
x.grad.zero_()

tensor(0.)

In [129]:
### Write gradient descent code of minimizing x**2+4x
x = torch.tensor(0.0,requires_grad=True)
lr = 0.01
for i in range(100):
    z = x**2+4*x ## forward pass
    z.backward()
    with torch.no_grad():
        x-=x.grad*lr
        x.grad.zero_()

In [130]:
x

tensor(-1.7348, requires_grad=True)

In [131]:
data = pd.read_csv("../data/regression.csv")
data.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0        8.0         307.0       130.0  3504.0          12.0  70.0   
1  15.0        8.0         350.0       165.0  3693.0          11.5  70.0   

   origin  
0     1.0  
1     1.0

In [161]:
X = data[['cylinders']].copy()
X['Ones'] = 1
X = X[['Ones','cylinders']].values
y = data['mpg'].values

In [162]:
X = torch.tensor(X,dtype=torch.int64)
y = torch.tensor(y,dtype=torch.int64)

In [163]:
W = torch.tensor([[1.0],[1.0]],requires_grad=True)
pred=torch.matmul(X.float(),W)

In [164]:
loss = torch.sum((pred-y)**2)/len(y)

In [165]:
loss

tensor(138607.5781, grad_fn=<DivBackward0>)

In [166]:
loss.backward()

In [167]:
W.grad

tensor([[-13447.9902],
        [-71058.4844]])

In [170]:
W = torch.tensor([[1.0],[1.0]],requires_grad=True)
lr = 0.000001
for i in range(100):
    pred=torch.matmul(X.float(),W)
    loss=torch.sum((pred-y)**2)/len(y)
    loss.backward()
    with torch.no_grad():
        W-=lr*W.grad
        W.grad.zero_()
print(W)

tensor([[1.5669],
        [3.4667]], requires_grad=True)


In [171]:
data = pd.read_csv("../data/classification.csv")

In [172]:
X = data[['No_pregnant']].copy()
X['Ones'] = 1
X = X[['Ones','No_pregnant']].values
y = data['Class'].values
X = torch.tensor(X,dtype=torch.int64)
y = torch.tensor(y,dtype=torch.int64)

In [184]:
tol=0.0000000000001
W = torch.tensor([[1.0],[1.0]],requires_grad=True)
z = torch.matmul(X.float(),W)
p = 1.0/(1+torch.exp(-z))
loss = (y*torch.log(p+tol)+(1-y)*torch.log(1-p+tol)).mean()

tensor(-3.2408, grad_fn=<MeanBackward0>)

torch.Size([768, 768])

In [185]:
tol=0.0000000000001
W = torch.tensor([[1.0],[1.0]],requires_grad=True)
lr = 0.0001
for i in range(100):
    z = torch.matmul(X.float(),W)
    p = 1.0/(1+torch.exp(-z))
    loss = -1*(y*torch.log(p+tol)+(1-y)*torch.log(1-p+tol)).mean()
    loss.backward()
    with torch.no_grad():
        W-=lr*W.grad
        W.grad.zero_()
W

tensor([[0.9814],
        [0.7562]], requires_grad=True)

In [186]:
local_path_mnist_train = "/Users/gunnvantsaini/OneDrive/project_codes/content/dl_basics/vision/sony/data/mnist_train.csv"
local_path_mnist_test = "/Users/gunnvantsaini/OneDrive/project_codes/content/dl_basics/vision/sony/data/mnist_test.csv"

In [187]:
mnist_train = pd.read_csv(local_path_mnist_train)
mnist_test = pd.read_csv(local_path_mnist_test)

In [189]:
mnist_train.shape

(42000, 785)

In [188]:
from torch import nn

In [229]:
class Mod(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(784,3)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(3,10)
        self.softmax = nn.Softmax()
    def forward(self,x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.softmax(x)
        return x
        

In [230]:
model = Mod()

In [202]:
[p for p in model.parameters()]

[Parameter containing:
 tensor([[-0.0199, -0.0245, -0.0211,  ..., -0.0312,  0.0098,  0.0181],
         [ 0.0166, -0.0228, -0.0267,  ..., -0.0217, -0.0205,  0.0065],
         [-0.0300,  0.0327, -0.0339,  ...,  0.0164, -0.0135,  0.0206]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0293, -0.0159, -0.0084], requires_grad=True),
 Parameter containing:
 tensor([[ 0.2328, -0.0020,  0.2247],
         [ 0.2015, -0.3035, -0.4244],
         [-0.5117,  0.1465,  0.0755],
         [-0.0398,  0.0123,  0.2932],
         [ 0.3793,  0.0928, -0.5581],
         [ 0.3465,  0.1177, -0.4535],
         [-0.0839,  0.3049,  0.0086],
         [-0.0598,  0.1644,  0.1615],
         [-0.3422,  0.4285,  0.5558],
         [-0.1740, -0.3695,  0.2924]], requires_grad=True),
 Parameter containing:
 tensor([-0.0331,  0.0233, -0.4222, -0.4142, -0.0436, -0.4742, -0.4731,  0.0416,
         -0.1151, -0.2387], requires_grad=True)]

In [203]:
loss_fn=nn.CrossEntropyLoss()

In [204]:
from torch.utils.data import Dataset, DataLoader

In [205]:
l = [1,2,3,4,5]

In [206]:
l[0]

1

In [207]:
len(l)

5

In [208]:
class mnist(Dataset):
    def __init__(self,X,y):
        self.X = X
        self.y = y
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self,idx):
        x = self.X[idx]
        y = self.y[idx]
        return {'X':x,'y':y}
        

In [212]:
X = mnist_train.drop('label',axis=1).values

In [213]:
y = mnist_train['label'].values

In [214]:
m = mnist(X,y)

In [215]:
mnist_batched_data = DataLoader(m,batch_size=2)

In [222]:
next(iter(mnist_batched_data))

{'X': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]),
 'y': tensor([1, 0])}

In [232]:
num_epochs = 10
lr = 10
for i in range(num_epochs):
    for batch in mnist_batched_data:
        x = batch['X'].float()
        y = batch['y']
        p=model(x)
        loss = loss_fn(p,y)
        loss.backward()
        with torch.no_grad():
            for param in model.parameters():
                param-=lr*param.grad
                param.grad.zero_()

/var/folders/7h/01sjg2sx6tl3y72r2klm24c80000gn/T/ipykernel_20222/2792426290.py:12: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = self.softmax(x)
